name 'netapp-psp'
maintainer 'Thomas Heinen'
maintainer_email 'theinen@tecracer.de'
issues_url 'https://github.com/tecracer-theinen/netapp-psp'
source_url 'https://github.com/tecracer-theinen/netapp-psp'
license 'Apache-2.0'
description 'Chef PSP for NetApp ONTAP'
version '0.1.0'
chef_version '>= 18.0'
